name: Android Auto-Deploy

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Choose the Client'
        required: true
        type: choice
        options: [ clientA, clientB ]
      track:
        description: 'Store Phase'
        required: true
        type: choice
        options: [ internal, beta ]
      core_branch:
        description: 'Rama del Core'
        required: true
        default: 'develop'
      api_branch:
        description: 'Rama de la API'
        required: true
        default: 'develop'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clone Core code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.core_branch }}
          fetch-depth: 0

      - name: Merge API code
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          # Trae la rama de la API y la fusiona localmente
          git fetch origin ${{ github.event.inputs.api_branch }}
          git merge origin/${{ github.event.inputs.api_branch }} --no-commit --no-ff || echo "Nada que mergear o conflictos manejados"

      # ... (Aquí continúan tus steps: Assign Exact Secrets, Decode Files, Fastlane...)